// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUzQ3XNRuW0S3pne96t83nGevtmay2ptY',
    appId: '1:1070725071429:web:6cecc67e969b54d0fa992c',
    messagingSenderId: '1070725071429',
    projectId: 'spendza-7c888',
    authDomain: 'spendza-7c888.firebaseapp.com',
    storageBucket: 'spendza-7c888.firebasestorage.app',
    measurementId: 'G-GN9ZZ34852',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyMgvcbPwQO6HqRibEOIyWCn5BSJhK0NA',
    appId: '1:1070725071429:android:c233920e28fbd48bfa992c',
    messagingSenderId: '1070725071429',
    projectId: 'spendza-7c888',
    storageBucket: 'spendza-7c888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdmHixusbH8jBMf-t_mgJ9f0uF5eOnDfU',
    appId: '1:1070725071429:ios:26fce767c380632afa992c',
    messagingSenderId: '1070725071429',
    projectId: 'spendza-7c888',
    storageBucket: 'spendza-7c888.firebasestorage.app',
    iosBundleId: 'com.example.spendza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdmHixusbH8jBMf-t_mgJ9f0uF5eOnDfU',
    appId: '1:1070725071429:ios:26fce767c380632afa992c',
    messagingSenderId: '1070725071429',
    projectId: 'spendza-7c888',
    storageBucket: 'spendza-7c888.firebasestorage.app',
    iosBundleId: 'com.example.spendza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUzQ3XNRuW0S3pne96t83nGevtmay2ptY',
    appId: '1:1070725071429:web:1154a65b66d9363afa992c',
    messagingSenderId: '1070725071429',
    projectId: 'spendza-7c888',
    authDomain: 'spendza-7c888.firebaseapp.com',
    storageBucket: 'spendza-7c888.firebasestorage.app',
    measurementId: 'G-8ZLSX0KSY9',
  );
}
